import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link' 
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //Este hook sirve...
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Devtter 🐦</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>        
        <h1>
            <a href='https://nextjs.org/' target={'_blank'}>Devtter</a>
        </h1>
        <nav>
          <Link className='link' href='/timeline'>Timeline</Link>
        </nav>
      </main>
    </>
  )
}
